"""migrate

Revision ID: 9aa8657337de
Revises: 
Create Date: 2025-02-22 23:26:46.114752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aa8657337de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_points', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('last_trivia_attempt', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_trivia_attempt')
        batch_op.drop_column('total_points')

    # ### end Alembic commands ###
